"""Create inventory table

Revision ID: 3b1631458dd8
Revises: 
Create Date: 2026-03-18 15:35:09.770246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1631458dd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('fnsku', sa.String(), nullable=True),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('fulfillment_center_id', sa.String(), nullable=False),
    sa.Column('fulfillable_quantity', sa.Integer(), nullable=False),
    sa.Column('unfulfillable_quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('inbound_working_quantity', sa.Integer(), nullable=False),
    sa.Column('inbound_shipped_quantity', sa.Integer(), nullable=False),
    sa.Column('inbound_receiving_quantity', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', 'fulfillment_center_id', 'condition', name='uq_sku_fc_condition')
    )
    op.create_index(op.f('ix_inventory_asin'), 'inventory', ['asin'], unique=False)
    op.create_index(op.f('ix_inventory_fnsku'), 'inventory', ['fnsku'], unique=False)
    op.create_index(op.f('ix_inventory_fulfillment_center_id'), 'inventory', ['fulfillment_center_id'], unique=False)
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_sku'), 'inventory', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_sku'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_fulfillment_center_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_fnsku'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_asin'), table_name='inventory')
    op.drop_table('inventory')
    # ### end Alembic commands ###
