"""add orders

Revision ID: 529845055c45
Revises: 3b1631458dd8
Create Date: 2026-03-18 17:33:09.660995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529845055c45'
down_revision: Union[str, Sequence[str], None] = '3b1631458dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amazon_order_id', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_status', sa.String(), nullable=True),
    sa.Column('fulfillment_channel', sa.String(), nullable=True),
    sa.Column('sales_channel', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('item_status', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('item_price', sa.Float(), nullable=True),
    sa.Column('item_tax', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amazon_order_id', 'sku', name='uq_order_sku')
    )
    op.create_index(op.f('ix_orders_amazon_order_id'), 'orders', ['amazon_order_id'], unique=False)
    op.create_index(op.f('ix_orders_purchase_date'), 'orders', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_orders_sku'), 'orders', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_sku'), table_name='orders')
    op.drop_index(op.f('ix_orders_purchase_date'), table_name='orders')
    op.drop_index(op.f('ix_orders_amazon_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
